sudo: required
services:
  - docker

before_install:
  - docker build -t msprasanth12/docker-react -f Dockerfile.dev .

script:
  - docker run msprasanth12/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-080321924797"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "AWS_SECRET_ACCESS-KEY"
